# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Fri Mar 30 15:41:08 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(715, 569)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.txtHostname = QtGui.QLineEdit(self.centralwidget)
        self.txtHostname.setObjectName(_fromUtf8("txtHostname"))
        self.horizontalLayout.addWidget(self.txtHostname)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinPort = QtGui.QSpinBox(self.centralwidget)
        self.spinPort.setMinimum(1)
        self.spinPort.setMaximum(65536)
        self.spinPort.setObjectName(_fromUtf8("spinPort"))
        self.horizontalLayout_2.addWidget(self.spinPort)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.cmdConnect = QtGui.QPushButton(self.centralwidget)
        self.cmdConnect.setObjectName(_fromUtf8("cmdConnect"))
        self.horizontalLayout_3.addWidget(self.cmdConnect)
        self.cmdDisconnect = QtGui.QPushButton(self.centralwidget)
        self.cmdDisconnect.setEnabled(False)
        self.cmdDisconnect.setObjectName(_fromUtf8("cmdDisconnect"))
        self.horizontalLayout_3.addWidget(self.cmdDisconnect)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.groupBox = QtGui.QGroupBox(self.splitter_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.boardLayout = QtGui.QHBoxLayout(self.groupBox)
        self.boardLayout.setObjectName(_fromUtf8("boardLayout"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.listView_2 = QtGui.QListView(self.groupBox_2)
        self.listView_2.setObjectName(_fromUtf8("listView_2"))
        self.verticalLayout.addWidget(self.listView_2)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listView = QtGui.QListView(self.groupBox_3)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout_2.addWidget(self.listView)
        self.cmdSpectate = QtGui.QPushButton(self.groupBox_3)
        self.cmdSpectate.setEnabled(False)
        self.cmdSpectate.setObjectName(_fromUtf8("cmdSpectate"))
        self.verticalLayout_2.addWidget(self.cmdSpectate)
        self.cmdJoin = QtGui.QPushButton(self.groupBox_3)
        self.cmdJoin.setEnabled(False)
        self.cmdJoin.setObjectName(_fromUtf8("cmdJoin"))
        self.verticalLayout_2.addWidget(self.cmdJoin)
        self.cmdHost = QtGui.QPushButton(self.groupBox_3)
        self.cmdHost.setEnabled(False)
        self.cmdHost.setObjectName(_fromUtf8("cmdHost"))
        self.verticalLayout_2.addWidget(self.cmdHost)
        self.cmdStart = QtGui.QPushButton(self.groupBox_3)
        self.cmdStart.setEnabled(False)
        self.cmdStart.setObjectName(_fromUtf8("cmdStart"))
        self.verticalLayout_2.addWidget(self.cmdStart)
        self.verticalLayout_3.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label.setBuddy(self.txtHostname)
        self.label_2.setBuddy(self.spinPort)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.cmdConnect, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.connect_server)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.cmdSpectate, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.spectate)
        QtCore.QObject.connect(self.cmdJoin, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.join)
        QtCore.QObject.connect(self.cmdHost, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.host)
        QtCore.QObject.connect(self.cmdStart, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.start)
        QtCore.QObject.connect(self.cmdDisconnect, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.socket_disconnected)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Chinese Checkers", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDisconnect.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Board", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Players", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Games", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSpectate.setText(QtGui.QApplication.translate("MainWindow", "Spectate", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdJoin.setText(QtGui.QApplication.translate("MainWindow", "Join", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdHost.setText(QtGui.QApplication.translate("MainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

